---
title: "nasal_exp_deg_comparison_010924_vs_080724"
author: "youngjinkim"
date: "2024-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
two nasal DEG ~ blood were performed once 010924 and once 080724. first had batch 1234, less samples, and some samples had large nasal-cbc sampling interval.  in the newer analysis, batch 12346, more samples, and the sampling interval was limited to less than 1 yr. 

```{r , echo=FALSE}
library(dplyr)
library(pheatmap)
library(tidyverse)
file_path<-"./reports/local_only/nasal_comparison_01-09-24_vs_08-07-24/nasal_comp.txt"
file.exists(file_path)
ncomp<-read.table(file_path,row.names=NULL,header=TRUE)
res<-unique(ncomp$res)
# ncomp%>%filter(res==res[1])%>%mutate_at(vars(log2FoldChange),rank)
# # 
# ncomp<-ncomp%>%group_by(res)%>%mutate_at(vars(log2FoldChange),rank)
ncomp_pivot<-pivot_wider(ncomp%>%select(res,genes,log2FoldChange),values_from = log2FoldChange,names_from = res,values_fill = 0)

ncomp_matrix<-ncomp_pivot[,-1]%>%as.matrix()
rownames(ncomp_matrix)<-ncomp_pivot$genes

```

```{r}
plot(x=ncomp_pivot$`n~bld_eos_p_cont_all`,y=ncomp_pivot$`n~bld_aec_cont_mt0`)
model<-lm(data=ncomp_pivot,`n~bld_aec_cont_mt0`~`n~bld_eos_p_cont_all`)
abline(model, col='red',lwd=2)
```
basically, some genes are not DEG in either experiments, but no genes had opposite directions in two experiments. 